config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web, at: '/sidekiq'
  resources :states#, :defaults => { :format => 'json' }
  resources :countries#, :defaults => { :format => 'json' }
  get '/get_states/:country_id' => 'states#get_states_based_county'#, :defaults => { :format => 'json' }
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'otp_confrimation', to: "home#testing"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states, dependent: :destroy
	validates :name, uniqueness: true
end

app/models/state.rb
class State < ApplicationRecord
	belongs_to :country
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    byebug
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require "faraday"
  require 'net/http'
  require 'uri'


  def index
    # FirstWorker.perform_at(5.minutes.from_now)
  end
  def testing



    # url = URI('https://hrms-finance.b91002.dev.us-east-1.aws.svc.builder.cafe/bx_block_login/login/login_otp_confirmation')
    # header = {'Content-Type': 'text/json'}
    # debugger
    # https = Net::HTTP.new(url.host, url.port);
    # https.use_ssl = true
    # request = Net::HTTP::Post.new(url, header)
    # request.body = {"data": {"type": "email_otp", "token": "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NTUsImV4cCI6MTY2OTE5OTM1NCwidHlwZSI6IkFjY291bnRCbG9jazo6RW1haWxPdHAiLCJhY2NvdW50X2lkIjoxMjF9.Q7qRdu-AsWaI-ozd_-N0cu9o-6l2DttkYLWA1slrCWWp3LCE_bCszN5d2CSU24Zh_Xwy6kg7BRYI_gE-0OmfVw", "otp_code": "8212"}}.to_json
    # res = https.request(request)
    # debugger

    # uri = URI('https://hrms-finance.b91002.dev.us-east-1.aws.svc.builder.cafe/bx_block_login/login/login_otp_confirmation')
    # params = {"data": {"type": "email_otp", "token": "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NTUsImV4cCI6MTY2OTE5OTM1NCwidHlwZSI6IkFjY291bnRCbG9jazo6RW1haWxPdHAiLCJhY2NvdW50X2lkIjoxMjF9.Q7qRdu-AsWaI-ozd_-N0cu9o-6l2DttkYLWA1slrCWWp3LCE_bCszN5d2CSU24Zh_Xwy6kg7BRYI_gE-0OmfVw", "otp_code": "8212"}}
    # req = Net::HTTP::Post.new(uri.path, {'Content-Type' => 'application/json'})
    # req.body = req
    # res = http.request(req)

    # @response = JSON.parse(res.body)
    # debugger


    
    @resp = Faraday.post do |req|
      req.headers[:Content_Type] = 'application/json'
      req.url 'https://hrms-finance.b91002.dev.us-east-1.aws.svc.builder.cafe/bx_block_login/login/login_otp_confirmation'
      params = {"data": {"type": "email_otp", "token": "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NTcsImV4cCI6MTY2OTIyMzU1MiwidHlwZSI6IkFjY291bnRCbG9jazo6RW1haWxPdHAiLCJhY2NvdW50X2lkIjoxMjF9.qeFTE5lTAPINO3n4uXw9mWgzvGrnr7ueH6jIFAVdHomSCE56-PM7XawhtqIE5lg7uVJdGvzmrzupjQOOadM3eA", "otp_code": "4784"}}
      req.body = params.to_json
    end
    @reponse = JSON.parse(@resp.body).merge("status" => @resp.status)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    # @states = State.joins("INNER JOIN countries c on c.id = states.country_id").where("c.id LIKE ?", params[:country_id])
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_states_based_county
    @states = State.joins("INNER JOIN countries c on c.id = states.country_id").where("c.id LIKE ?", params[:country_id])
    render "index"
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name, :country_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <%= country_select("rr", "country", { include_blank: 'Select a country' }, { class: 'country-select-box' }) %>

  <%= country_select("ss", "country", priority_countries: ["GB", "FR", "DE"], sort_provided: false) %>
  <%#= form.input :country_field, collection: CountryStateSelect.countries_collection %>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Countries</h1>

<div id="countries">
  <% @countries.each do |country| %>
    <%= render country %>
    <p>
      <%= link_to "Show this country", country %>
    </p>
  <% end %>
</div>

<%= link_to "New country", new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<form id="get_event">
<input type='button' onclick="submitFrmAjax();" value="Change City" id="scsd">
</form>

<button class="vendor-link">dcdf</button>



<a href="/otp_confrimation">xyz</a>

<script>
	function submitFrmAjax(){
	 $.ajax({
	    type:'POST', 
	    url: 'https://hrms-finance.b91002.dev.us-east-1.aws.svc.builder.cafe/bx_block_login/login/login_otp_confirmation', 
	    data: {"data": {"type": "email_otp", "token": "eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NTUsImV4cCI6MTY2OTE5OTM1NCwidHlwZSI6IkFjY291bnRCbG9jazo6RW1haWxPdHAiLCJhY2NvdW50X2lkIjoxMjF9.Q7qRdu-AsWaI-ozd_-N0cu9o-6l2DttkYLWA1slrCWWp3LCE_bCszN5d2CSU24Zh_Xwy6kg7BRYI_gE-0OmfVw", "otp_code": "8212"}}
	  });
	}
	
</script>

app/views/home/testing.html.erb
sdsdds

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleDummyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.number_field :country_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Name:</strong>
    <%= state.name %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= state.country_id %>
  </p>

</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>States</h1>

<div id="states">
  <% @states.each do |state| %>
    <%= render state %>
    <p>
      <%= link_to "Show this state", state %>
    </p>
  <% end %>
</div>

<%= link_to "New state", new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>